
export const SET_COLOR_ALL = "SET_COLOR_ALL";
export const SET_COLOR_ALL_SUCCESS = "SET_COLOR_ALL_SUCCESS";
export const SET_COLOR_ALL_FAILURE = "SET_COLOR_ALL_FAILURE";

export const SET_COLOR_ONE = "SET_COLOR_ONE";
export const SET_COLOR_ONE_SUCCESS = "SET_COLOR_ONE_SUCCESS";
export const SET_COLOR_ONE_FAILURE = "SET_COLOR_ONE_FAILURE";

export const SET_BRIGHTNESS = "SET_BRIGHTNESS";
export const SET_BRIGHTNESS_SUCCESS = "SET_BRIGHTNESS_SUCCESS";
export const SET_BRIGHTNESS_FAILURE = "SET_BRIGHTNESS_FAILURE";

export const SET_ANIMATION = "SET_ANIMATION";
export const SET_ANIMATION_SUCCESS = "SET_ANIMATION_SUCCESS";
export const SET_ANIMATION_FAILURE = "SET_ANIMATION_FAILURE";